# On définit les types MIME globalement
types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                js;
    application/atom+xml                  atom;
    application/rss+xml                   rss;
    font/woff                             woff;
    font/woff2                            woff2;
    image/png                             png;
    image/svg+xml                         svg svgz;
    image/webp                            webp;
    application/json                      json;
}

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # On force le type JS pour tout ce qui finit en .js ou .jsx dans assets
    location ~* \.(?:js|jsx)$ {
        root /usr/share/nginx/html;
        add_header Content-Type application/javascript;
    }
}