services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - task_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: todo_list
    volumes:
      # On monte le code du backend dans /app/backend pour correspondre au Dockerfile
      - ./backend:/app/backend
      # On monte le dossier frontend à côté pour que "../frontend" dans server.js fonctionne
      - ./frontend:/frontend
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  task_data: